### ISSUE TITLE
Can I use this tool with Ngnix and OpenLiteSpeed?

### ISSUE THREAD

**Issue by blakstrox** [furkannibis/waffox#1]
Thank you so much for this tool. I have some questions. Can you help me with these?

Is any pre-trained model available?
Is this like ModSecurity?
Is this stable enough to be used in a Production Server?
How can integrate this tool with Nginx and OpenLiteSpeed using a Python script?

**Comment by furkannibis** [comment]
Unfortunately, a dataset has been developed for Waffox by capturing and analyzing real-time packets from various important web devices. Therefore, it is not possible for us to share the existing dataset, we apologize. Additionally, Waffox is a simple web application firewall project that performs user request handling based on rules defined by the developer, similar to ModSecurity. The stability of the project has not been tested yet. The only testing process involved creating malicious and normal values written on Ethernet, IP, TCP, and HTTP packets using the Python Scapy module. It is still too early to provide a guarantee in this regard. In the Nginx or OpenLiteSpeed configuration, you should adjust the incoming requests to communicate with this Python script through a specific port. You can choose an appropriate port to run the script.

**Comment by furkannibis** [comment]
Yes, Waffox utilizes supervised machine learning. It trains a model using a labeled dataset and then performs operations using that model. A labeled dataset consists of examples that contain the correct answers. This enables the model to analyze input data and make accurate predictions. However, please remember that you need a dataset in the required topics. Waffox initially creates a trained model using this dataset and subsequently performs operations on that model to save you time during the training process. However, the important point to note is that currently, Waffox can only operate under the following attack topics:

    SQL Injection
    Cross-Site Scripting
    Command Injection
    Path Traversal
    DoS
    Additionally, it can block packets containing forbidden words determined by the admin.
